spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://8.219.131.180:8765/fintrack
    username: root
    password: P@SSWORD666
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 1
  sql:
    init:
      platform: postgres




